# Generated by Django 5.2.8 on 2025-11-16 16:01

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Habit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Название привычки')),
                ('startTime', models.TimeField(verbose_name='Время начало привычки')),
                ('endTime', models.TimeField(verbose_name='Время конца привычки')),
                ('startHabitDate', models.DateField(auto_now_add=True, verbose_name='Дата создания привычки')),
                ('endHabitDate', models.DateField(verbose_name='Дата окончания привычки')),
                ('targetHabit', models.CharField(max_length=500, verbose_name='Цель привычки')),
                ('days', models.IntegerField(verbose_name='Количество дней')),
                ('habitUser', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Пользователь привычки')),
            ],
            options={
                'verbose_name': 'Привычка',
                'verbose_name_plural': 'Привычки',
            },
        ),
    ]
