# Generated by Django 5.2.8 on 2025-11-16 18:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_habitlog'),
    ]

    operations = [
        migrations.AlterField(
            model_name='habitlog',
            name='habit',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='habit_logs', to='api.habit', verbose_name='Привычка'),
        ),
    ]
