# Generated by Django 5.2.8 on 2025-11-23 12:12

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_alter_news_title'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('telegram_key', models.IntegerField(blank=True, null=True, verbose_name='Ключ для связи телеграм')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Пользователь профиля')),
            ],
        ),
        migrations.CreateModel(
            name='TelegramDeviсe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('telegramId', models.IntegerField(verbose_name='телеграм ID пользователя')),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='telegram_devices', to='api.userprofile', verbose_name='Профиль девайса')),
            ],
        ),
    ]
