# Generated by Django 5.2.8 on 2025-11-23 12:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_userprofile_telegramdeviсe'),
    ]

    operations = [
        migrations.AlterField(
            model_name='telegramdeviсe',
            name='telegramId',
            field=models.IntegerField(unique=True, verbose_name='телеграм ID пользователя'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='telegram_key',
            field=models.IntegerField(blank=True, null=True, unique=True, verbose_name='Ключ для связи телеграм'),
        ),
    ]
