# Generated by Django 5.2.8 on 2025-11-23 17:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0011_alter_telegramdeviсe_telegramid_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='habit',
            name='active',
            field=models.BooleanField(default=True),
        ),
    ]
