# Generated by Django 5.2.8 on 2025-11-23 19:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0012_habit_active'),
    ]

    operations = [
        migrations.AlterField(
            model_name='telegramdeviсe',
            name='profile',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='telegram_devices', to='api.userprofile', verbose_name='Профиль девайса'),
        ),
    ]
