# Generated by Django 5.2.8 on 2025-11-23 19:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0013_alter_telegramdeviсe_profile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='telegramdeviсe',
            name='profile',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='telegram_device', to='api.userprofile', verbose_name='Профиль девайса'),
        ),
    ]
