# Generated by Django 5.2.8 on 2025-11-25 18:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0016_targetmoney'),
    ]

    operations = [
        migrations.AlterField(
            model_name='targetmoney',
            name='current_amount',
            field=models.IntegerField(default=0, verbose_name='Нынешняя сумма'),
        ),
    ]
