# Generated by Django 5.2.8 on 2025-11-29 12:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0017_alter_targetmoney_current_amount'),
    ]

    operations = [
        migrations.AlterField(
            model_name='telegramdeviсe',
            name='telegramId',
            field=models.BigIntegerField(unique=True, verbose_name='телеграм ID пользователя'),
        ),
    ]
