# Generated by Django 5.2.8 on 2025-11-29 16:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0018_alter_telegramdeviсe_telegramid'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='TelegramDeviсe',
            new_name='TelegramDevice',
        ),
    ]
