# Generated by Django 5.2.8 on 2025-11-29 17:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0019_rename_telegramdeviсe_telegramdevice'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='is_allowed_notf',
            field=models.BooleanField(default=False),
        ),
    ]
