# Generated by Django 5.2.8 on 2025-11-29 17:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0020_userprofile_is_allowed_notf'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='is_allowed_notf',
        ),
    ]
